#!/bin/sh
# Resolve all dependencies that the application requires to run.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

pip3 install uv

echo "Creating venv..."
uv venv

echo "Installing development dependencies..."
uv sync
